# Generated by Django 5.0.3 on 2024-06-09 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Comptes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilisateur',
            name='nom',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='whatsapp',
            field=models.CharField(blank=True, max_length=13, null=True),
        ),
    ]
