# Generated by Django 5.0.3 on 2024-06-11 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Comptes', '0002_alter_utilisateur_nom_alter_utilisateur_whatsapp'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisateur',
            name='email_verified',
            field=models.BooleanField(default=False),
        ),
    ]
