# Generated by Django 5.0.3 on 2024-05-25 20:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Signalement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now=True)),
                ('Auteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SignalementColloc',
            fields=[
                ('signalement_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='GofindApp.signalement')),
                ('titre', models.CharField(max_length=128)),
                ('Photo1', models.ImageField(upload_to='imagesMaisons')),
                ('Photo2', models.ImageField(blank=True, null=True, upload_to='imagesMaisons')),
                ('Photo3', models.ImageField(blank=True, null=True, upload_to='imagesMaisons')),
                ('details', models.TextField()),
                ('lieu', models.CharField(default='YAOUNDE', max_length=128)),
                ('prix', models.IntegerField()),
                ('nombre', models.IntegerField()),
            ],
            bases=('GofindApp.signalement',),
        ),
        migrations.CreateModel(
            name='SignalementObjet',
            fields=[
                ('signalement_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='GofindApp.signalement')),
                ('Code', models.CharField(max_length=328)),
                ('nom', models.CharField(max_length=328)),
                ('Photo1', models.ImageField(upload_to='imagesVoiture')),
                ('Photo2', models.ImageField(blank=True, null=True, upload_to='imagesVoiture')),
                ('Photo3', models.ImageField(blank=True, null=True, upload_to='imagesVoiture')),
                ('description', models.TextField()),
                ('lieu', models.CharField(default='YAOUNDE', max_length=128)),
                ('cathegorie', models.CharField(max_length=200)),
            ],
            bases=('GofindApp.signalement',),
        ),
        migrations.CreateModel(
            name='SignalementTrajet',
            fields=[
                ('signalement_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='GofindApp.signalement')),
                ('Depart', models.CharField(max_length=128)),
                ('Arrive', models.CharField(max_length=128)),
                ('Photo1', models.ImageField(upload_to='imagesVoiture')),
                ('Photo2', models.ImageField(blank=True, null=True, upload_to='imagesVoiture')),
                ('Photo3', models.ImageField(blank=True, null=True, upload_to='imagesVoiture')),
                ('commentaire', models.TextField()),
                ('lieu', models.CharField(default='YAOUNDE', max_length=128)),
                ('prix', models.IntegerField()),
                ('places', models.IntegerField()),
                ('dateDepart', models.DateTimeField()),
                ('modeleVoiture', models.CharField(max_length=200)),
            ],
            bases=('GofindApp.signalement',),
        ),
    ]
